# ./gradlew build -x test
# docker-compose -p concert up -d
# docker-compose -p concert up --build -d
services:

  application-server:
    container_name: spring-boot
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../config/slack.properties:/app/config/slack.properties
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/hhplus?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "zjxA8!9d*a"
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true" # Micrometer Prometheus 활성화
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus" # Prometheus 엔드포인트 노출

    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - concert

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0   # 안정적인 MySQL 8.0 버전 사용
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: zjxA8!9d*a
      MYSQL_DATABASE: hhplus
      MYSQL_USER: concert
      MYSQL_PASSWORD: d&xjzlAX7z@L
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - concert

  redis:
    container_name: redis
    image: redis:7.0    # 최신 안정 버전의 Redis 사용
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]  # 데이터 영속성 활성화
    networks:
      - concert

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    # Mac M chip 사용 시 아래 platform 추가
    platform: linux/amd64
    networks:
      - concert

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - concert

#  k6:
#    image: grafana/k6
#    volumes:
#      - ../k6/test.js:/test/test.js
#    command: [ "run", "/test/test.js" ]
#    depends_on:
#      - application-server
#    networks:
#      - concert

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - concert

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - concert

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - concert

networks:
  concert:

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
