global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus' # Spring Micrometer 엔드포인트
    static_configs:
      - targets:
          - 'spring-boot:8080' # Spring 애플리케이션의 컨테이너 이름

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
