TRUNCATE TABLE ticket;

-- Ticket 데이터 삽입
SET @seat_no = 0;
INSERT INTO ticket (concert_schedule_id, type, price, seat_no)
SELECT
    FLOOR(1 + RAND() * 1000) AS concert_schedule_id,          -- 1부터 1000 사이의 랜덤 공연 일정 ID
    CASE FLOOR(RAND() * 3)                                    -- 티켓 타입 랜덤 선택 (0, 1, 2)
        WHEN 0 THEN 'VIP'
        WHEN 1 THEN 'FIRST'
        WHEN 2 THEN 'SECOND'
        ELSE 'SECOND'                                         -- 기본값으로 'SECOND'
        END AS type,
    FLOOR(5000 + RAND() * 50000) AS price,                    -- 5000에서 50000 사이의 랜덤 가격
    CONCAT('A', @seat_no := @seat_no + 1) AS seat_no         -- 좌석 번호를 A1, A2, A3 ... 순으로 증가
FROM
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS a
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS b
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS c
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS d
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS e
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS f;

-- 데이터 확인
SELECT COUNT(*) FROM ticket;

-- 인덱스 추가
CREATE INDEX idx_ticket ON ticket (concert_schedule_id, type, price);

-- 인덱스 제거
DROP INDEX idx_ticket ON ticket;

-- 특정 조건으로 검색
EXPLAIN
SELECT *
FROM ticket
WHERE
    concert_schedule_id = 4
  AND type = 'VIP'
  AND price BETWEEN 10000 AND 30000;
