TRUNCATE TABLE concert_schedule;

INSERT INTO concert_schedule (concert_id, is_sold_out, total_seat, available_seat, date_concert)
SELECT
    FLOOR(1 + RAND() * 100) AS concert_id,                    -- 1부터 100 사이의 랜덤 concert_id
    RAND() < 0.5 AS is_sold_out,                              -- 랜덤 Boolean 값
    FLOOR(50 + RAND() * 200) AS total_seat,                   -- 50부터 250 사이의 랜덤 좌석 수
    GREATEST(FLOOR(RAND() * 200), 0) AS available_seat,       -- 예약 가능 좌석 수, totalSeat 이하로 설정
    DATE_ADD(NOW(), INTERVAL FLOOR(RAND() * 365) DAY)         -- 현재 날짜 기준 1년 이내 랜덤 날짜
FROM
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS a
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS b
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS c
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS d
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS e
        CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS f;


SELECT COUNT(*)
FROM concert_schedule
;

CREATE INDEX idx_concert_schedule ON concert_schedule (concert_id, is_sold_out, date_concert);
DROP INDEX idx_concert_schedule ON concert_schedule;

EXPLAIN
SELECT *
FROM concert_schedule
WHERE
    concert_id = 4
  AND is_sold_out = 0
  AND date_concert BETWEEN '2024-12-01' AND '2024-12-31'
